osx_image: xcode8.3

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv yarn-* $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - openssl aes-256-cbc -K $encrypted_5af690707dae_key -iv $encrypted_5af690707dae_iv -in utilities/.dropbox_uploader.enc -out ~/.dropbox_uploader -d

script:
  - yarn build:prod
  - yarn dist:all

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

after_success:
  - find dist/*.AppImage -exec ./utilities/dropbox_uploader.sh upload {} / \; 
  - find dist/*.dmg -exec ./utilities/dropbox_uploader.sh upload {} / \; 
  - find dist/*.exe -exec ./utilities/dropbox_uploader.sh upload {} / \; 

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
